server:
  port: ${port:8087} #服务端口

spring:
  application:
    name: eshop-one-service #指定服务名

  jackson:
    default-property-inclusion: non_null

#  zipkin:
#    enabled: true
#    baseUrl: http://eshop-zipkin-dashboard/
#  sleuth:
#    sampler:
#      #  默认值为0.1f，现在为了测试设置100%采集
#      percentage: 1

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: ${eurekaServerUrl:http://root:root@127.0.0.1:8090/eureka/}
  instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
      ip-address: ${ipAddress:127.0.0.1}

#开启hystrix配置
feign:
  hystrix:
    enabled: true